const fs = require('fs');
const { EmbedBuilder } = require('discord.js');

function checkAndResetSeason(client, players, guilds) {
    const now = new Date();
        const currentMonth = `${now.getFullYear()}-${now.getMonth() + 1}`;
            
                // 讀取上次結算的月份
                    let config = { lastReset: "" };
                        if (fs.existsSync('./config.json')) {
                                config = JSON.parse(fs.readFileSync('./config.json', 'utf8'));
                                    }

                                        // 如果當前月份不等於上次結算月份 -> 執行結算
                                            if (config.lastReset !== currentMonth && config.lastReset !== "") {
                                                    console.log(`[系統] 檢測到新月份 ${currentMonth}，開始結算上季獎勵...`);

                                                            // 1. 找出公會排名 (依積分)
                                                                    const sortedGuilds = Object.entries(guilds)
                                                                                .map(([name, data]) => ({ name, ...data }))
                                                                                            .sort((a, b) => (b.score || 0) - (a.score || 0));

                                                                                                    if (sortedGuilds.length > 0) {
                                                                                                                const winner = sortedGuilds[0];
                                                                                                                            
                                                                                                                                        // 2. 發放團體獎勵 (例如：第一名公會金庫 +50000)
                                                                                                                                                    winner.bank += 50000;
                                                                                                                                                                
                                                                                                                                                                            // 3. 發放個人獎勵並重置積分
                                                                                                                                                                                        // 這裡我們會遍歷所有玩家，重置積分前給予獎勵
                                                                                                                                                                                                    for (let id in players) {
                                                                                                                                                                                                                    const p = players[id];
                                                                                                                                                                                                                                    const contribution = p.contribution || 0;

                                                                                                                                                                                                                                                    // 獎勵邏輯：每 100 積分換 $1000 金幣
                                                                                                                                                                                                                                                                    if (contribution > 0) {
                                                                                                                                                                                                                                                                                        const bonus = Math.floor(contribution / 100) * 1000;
                                                                                                                                                                                                                                                                                                            p.money += bonus;
                                                                                                                                                                                                                                                                                                                                p.contribution = 0; // 重置個人貢獻
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                        // 4. 重置公會積分
                                                                                                                                                                                                                                                                                                                                                                                    for (let gName in guilds) {
                                                                                                                                                                                                                                                                                                                                                                                                    guilds[gName].score = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                // 5. 更新結算紀錄
                                                                                                                                                                                                                                                                                                                                                                                                                                        config.lastReset = currentMonth;
                                                                                                                                                                                                                                                                                                                                                                                                                                                fs.writeFileSync('./config.json', JSON.stringify(config, null, 2));
                                                                                                                                                                                                                                                                                                                                                                                                                                                        fs.writeFileSync('./players.json', JSON.stringify(players, null, 2));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                fs.writeFileSync('./guilds.json', JSON.stringify(guilds, null, 2));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return { success: true, winnerName: sortedGuilds[0]?.name };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 初次執行初始化
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (config.lastReset === "") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            config.lastReset = currentMonth;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fs.writeFileSync('./config.json', JSON.stringify(config, null, 2));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return { success: false };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                module.exports = { checkAndResetSeason };