const fs = require('fs');

module.exports = {
    name: 'admin',
        aliases: ['gm', '管理'],
            async execute(message, args, p, players) {
                    // 🔒 權限檢查：請務必把 '你的ID' 換成你真正的 Discord ID
                            const adminIDs = ['1292424394957918248']; 
                                    if (!adminIDs.includes(message.author.id)) {
                                                return message.reply("🚫 權限不足，無法干涉世界法則。");
                                                        }

                                                                const subCommand = args[0];

                                                                        // 1. 給物品：~admin item @玩家 物品名稱 數量
                                                                                // 例如：~admin item @自己 小型生命藥水 10
                                                                                        if (subCommand === 'item') {
                                                                                                    const target = message.mentions.users.first() || message.author;
                                                                                                                // 處理中文名稱：合併所有 args 從第 2 個開始到倒數第 2 個 (因為最後一個是數量)
                                                                                                                            const count = parseInt(args[args.length - 1]) || 1;
                                                                                                                                        const itemName = args.slice(1, -1).join(' ').replace(/<@!?\d+>/g, '').trim();

                                                                                                                                                    if (!itemName) return message.reply("❌ 請輸入物品名稱！用法：`~admin item @玩家 物品名稱 數量` ");

                                                                                                                                                                const targetData = players[target.id];
                                                                                                                                                                            if (targetData) {
                                                                                                                                                                                            targetData.inventory = targetData.inventory || {};
                                                                                                                                                                                                            targetData.inventory[itemName] = (targetData.inventory[itemName] || 0) + count;
                                                                                                                                                                                                                            
                                                                                                                                                                                                                                            message.reply(`🎁 **系統配發**：已給予 ${target.username} \`${itemName}\` x${count}！`);
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                        // 2. 給錢：~admin money @玩家 數量
                                                                                                                                                                                                                                                                                else if (subCommand === 'money') {
                                                                                                                                                                                                                                                                                            const target = message.mentions.users.first() || message.author;
                                                                                                                                                                                                                                                                                                        const amount = parseInt(args[args.length - 1]) || 0;
                                                                                                                                                                                                                                                                                                                    const targetData = players[target.id];
                                                                                                                                                                                                                                                                                                                                if (targetData) {
                                                                                                                                                                                                                                                                                                                                                targetData.money += amount;
                                                                                                                                                                                                                                                                                                                                                                message.reply(`💰 **系統發放**：已給予 ${target.username} $${amount.toLocaleString()} 金幣！`);
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                            // 3. 修復狀態：~admin fix @玩家
                                                                                                                                                                                                                                                                                                                                                                                                    else if (subCommand === 'fix') {
                                                                                                                                                                                                                                                                                                                                                                                                                const target = message.mentions.users.first() || message.author;
                                                                                                                                                                                                                                                                                                                                                                                                                            const targetData = players[target.id];
                                                                                                                                                                                                                                                                                                                                                                                                                                        if (targetData) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        targetData.hp = targetData.maxHp || 100;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        targetData.energy = 12;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        message.reply(`✨ **神蹟顯現**：已恢復 ${target.username} 的生命與體力！`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return message.reply("❓ **管理員權限說明：**\n`~admin item @玩家 物品名稱 數量` (支援中文)\n`~admin money @玩家 數量`\n`~admin fix @玩家` (回滿血體)");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 儲存修改
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fs.writeFileSync('./players.json', JSON.stringify(players, null, 2));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };