const { qualities, tiers, parts, weaponTypes } = require('../utils/equipData.js');
const fs = require('fs');

module.exports = {
    name: 'craft',
        aliases: ['合成', 'hc'], // 支援 ~合成 或 ~hc
            async execute(message, args, p, players) {
                    // --- 1. 中文與縮寫識別系統 ---
                            const lv = parseInt(args[0]);
                                    const typeInput = args[1];

                                            if (!lv || !typeInput) {
                                                        return message.reply("💡 **用法：**`~合成 [等級] [類型]`\n例：`~合成 10 弓`、`~合成 90 頭`\n(等級：10, 30, 50, 70, 90)");
                                                                }

                                                                        // 部位自動識別映射
                                                                                let part = "";
                                                                                        let type = typeInput;

                                                                                                const weaponList = ['劍', '弓', '矛'];
                                                                                                        const headList = ['頭', '頭盔', '頂'];
                                                                                                                const armorList = ['甲', '護甲', '衣服', '身'];
                                                                                                                        const bootsList = ['鞋', '靴子', '靴', '足'];

                                                                                                                                if (weaponList.includes(typeInput)) {
                                                                                                                                            part = "weapon";
                                                                                                                                                    } else if (headList.includes(typeInput)) {
                                                                                                                                                                part = "head";
                                                                                                                                                                            type = "頭盔";
                                                                                                                                                                                    } else if (armorList.includes(typeInput)) {
                                                                                                                                                                                                part = "armor";
                                                                                                                                                                                                            type = "護甲";
                                                                                                                                                                                                                    } else if (bootsList.includes(typeInput)) {
                                                                                                                                                                                                                                part = "boots";
                                                                                                                                                                                                                                            type = "靴子";
                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                            if (!part || !tiers[lv]) {
                                                                                                                                                                                                                                                                        return message.reply("❌ **辨識失敗！** 請輸入正確的等級與類型 (劍/弓/矛/頭/甲/鞋)。");
                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                        const tier = tiers[lv];
                                                                                                                                                                                                                                                                                                const recipeCost = lv * 100;

                                                                                                                                                                                                                                                                                                        // --- 2. 條件檢查 (材料、金幣、等級) ---
                                                                                                                                                                                                                                                                                                                if (p.level < lv) return message.reply(`❌ **等級不足！** 你需要 Lv.${lv} 才能製作這階裝備。`);
                                                                                                                                                                                                                                                                                                                        if (p.money < recipeCost) return message.reply(`❌ **金幣不足！** 合成需要 \`$${recipeCost}\`。`);
                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                        const hasMain = p.inventory[tier.material] || 0;
                                                                                                                                                                                                                                                                                                                                                const hasSub = p.inventory[tier.sub] || 0;
                                                                                                                                                                                                                                                                                                                                                        if (hasMain < 10 || hasSub < 5) {
                                                                                                                                                                                                                                                                                                                                                                    return message.reply(`❌ **材料不足！** 需要：\n📦 10x \`${tier.material}\` (你有: ${hasMain})\n📦 5x \`${tier.sub}\` (你有: ${hasSub})`);
                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                    // --- 3. 隨機決定品質 (賭狗時刻！) ---
                                                                                                                                                                                                                                                                                                                                                                                            const roll = Math.random() * 100;
                                                                                                                                                                                                                                                                                                                                                                                                    let finalQual = "White";
                                                                                                                                                                                                                                                                                                                                                                                                            let accum = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                    for (const [q, info] of Object.entries(qualities)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                accum += info.chance;
                                                                                                                                                                                                                                                                                                                                                                                                                                            if (roll <= accum) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            finalQual = q;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // --- 4. 計算屬性 ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const baseValue = lv * 10;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const qMult = qualities[finalQual].mult;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const pWeight = parts[part].weight;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let finalStat = Math.floor(baseValue * qMult * pWeight);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 武器類型額外修正
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let weaponLabel = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (part === "weapon") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const wType = weaponTypes[type] || weaponTypes["劍"];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        finalStat = Math.floor(finalStat * wType.atkBonus);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    weaponLabel = type;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // --- 5. 扣除與發放 ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            p.money -= recipeCost;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    p.inventory[tier.material] -= 10;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            p.inventory[tier.sub] -= 5;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const itemName = `${qualities[finalQual].label} ${tier.name}${weaponLabel || parts[part].name}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // 初始化設備槽
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    p.equipment = p.equipment || {};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            p.equipment.plus = p.equipment.plus || {};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            p.equipment[part] = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        name: itemName,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    stat: finalStat,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                quality: finalQual,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            plus: 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // --- 6. 存檔 ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    players[message.author.id] = p;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fs.writeFileSync('./players.json', JSON.stringify(players, null, 2));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return message.reply(`⚒️ **打造成功！**\n你獲得了：**${itemName}**\n🔹 基礎屬性：\`+${finalStat}\` ${parts[part].mainStat.toUpperCase()}\n💰 合成花費：\`$${recipeCost}\``);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };