const { EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle } = require('discord.js');
const fs = require('fs');

// 價格庫 (延用剛才的 80 種物品中的 Common 等級)
const commonPrices = {
    "🪵 乾燥的木頭": 5, "🧪 小型生命藥水": 5, "粘稠的史萊姆液": 5, "哥布林的尖牙": 5, "枯萎的野花": 5, "粗糙的碎石": 5, "蝙蝠的翅膀": 5, "柔軟的兔皮": 5, "純淨泉水": 5, "🍙 過期飯糰": 5,
        "⛓️ 鐵礦石": 15, "🧪 中型生命藥水": 15, "銅礦原石": 15, "生鏽的齒輪": 15, "廢鐵渣": 15, "黑煤炭": 15, "石英砂碎塊": 15, "生鏽的鑰匙": 15, "粗糙磨刀石": 15, "⚡ 能量飲料": 15,
            "📜 優質皮革": 30, "🧪 大型生命藥水": 30, "野獸厚皮毛": 30, "強韌蜘蛛絲": 30, "發光的孢子": 30, "腐爛的布料": 30, "彩色毒蕈": 30, "天然蜂蠟": 30, "🌀 加速捲軸": 30, "🪵 堅硬的橡木": 30,
                "❄️ 冰晶碎片": 60, "🩹 急救包": 60, "硬化的甲殼": 60, "殭屍的腐肉": 60, "厚實棉絨": 60, "凍僵的魚": 60, "純淨雪球": 60, "🧪 抗寒合劑": 60, "🍪 幸運餅乾": 60, "⛓️ 白銀錠": 60,
                    "🌑 焦黑岩石": 150, "🧪 超大型藥水": 150, "餘燼灰燼": 150, "黑鐵錠": 150, "惡魔斷角": 150, "熔岩殼殘片": 150, "高溫溶劑": 150, "🧪 狂暴藥劑": 150, "🧪 鐵壁藥劑": 150, "🔥 硫磺粉末": 150
                    };

                    module.exports = {
                        name: 'sellall',
                            async execute(message, args, p, players) {
                                    if (!p.inventory || Object.keys(p.inventory).length === 0) return message.reply("🎒 背包是空的，沒東西可賣。");

                                            // 1. 先試算這次能賣多少錢
                                                    let totalEarnings = 0;
                                                            let soldItemsCount = 0;
                                                                    for (const [itemName, count] of Object.entries(p.inventory)) {
                                                                                if (count > 0 && commonPrices[itemName]) {
                                                                                                totalEarnings += commonPrices[itemName] * count;
                                                                                                                soldItemsCount += count;
                                                                                                                            }
                                                                                                                                    }

                                                                                                                                            if (totalEarnings === 0) return message.reply("⚠️ 沒發現可以自動販售的普通物資。");

                                                                                                                                                    // 2. 建立確認 Embed 與按鈕
                                                                                                                                                            const confirmEmbed = new EmbedBuilder()
                                                                                                                                                                        .setTitle("💰 批量販售確認")
                                                                                                                                                                                    .setColor(0xf1c40f)
                                                                                                                                                                                                .setDescription(`你即將賣出所有 **普通等級** 的物資（共 \`${soldItemsCount}\` 件）。\n\n預計獲得金幣：\`$${totalEarnings}\`\n\n**⚠️ 注意：貴重物品與素材不會被賣出。**`);

                                                                                                                                                                                                        const row = new ActionRowBuilder().addComponents(
                                                                                                                                                                                                                    new ButtonBuilder().setCustomId('confirm_sell').setLabel('確認販售').setStyle(ButtonStyle.Success),
                                                                                                                                                                                                                                new ButtonBuilder().setCustomId('cancel_sell').setLabel('取消').setStyle(ButtonStyle.Danger)
                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                const response = await message.reply({ embeds: [confirmEmbed], components: [row] });

                                                                                                                                                                                                                                                        // 3. 建立收集器監聽按鈕點擊
                                                                                                                                                                                                                                                                const collector = response.createMessageComponentCollector({
                                                                                                                                                                                                                                                                            filter: i => i.user.id === message.author.id,
                                                                                                                                                                                                                                                                                        time: 30000 // 30秒內要決定
                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                        collector.on('collect', async i => {
                                                                                                                                                                                                                                                                                                                    if (i.customId === 'confirm_sell') {
                                                                                                                                                                                                                                                                                                                                    // 執行真正的販售邏輯
                                                                                                                                                                                                                                                                                                                                                    for (const itemName in p.inventory) {
                                                                                                                                                                                                                                                                                                                                                                        if (commonPrices[itemName]) p.inventory[itemName] = 0;
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                        p.money = (p.money || 0) + totalEarnings;

                                                                                                                                                                                                                                                                                                                                                                                                                        // 存檔
                                                                                                                                                                                                                                                                                                                                                                                                                                        players[message.author.id] = p;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        fs.writeFileSync('./players.json', JSON.stringify(players, null, 2));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await i.update({ content: `✅ 販售成功！你獲得了 \`$${totalEarnings}\` 金幣。`, embeds: [], components: [] });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await i.update({ content: "❌ 已取消販售。", embeds: [], components: [] });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            collector.stop();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            collector.on('end', (collected, reason) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (reason === 'time') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        response.edit({ content: "⏰ 確認超時，交易已取消。", embeds: [], components: [] });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };