const fs = require('fs');

module.exports = {
    name: 'use',
        aliases: ['使用', '喝', '吃'],
            async execute(message, args, p, players) {
                    if (!args[0]) return message.reply("💡 **用法：**`~use [物品名稱]` (例：`~use 藥水` 或 `~use 飯糰`) ");

                            const searchKeyword = args[0];

                                    // 🔍 在背包尋找符合關鍵字的物品
                                            const realItemName = Object.keys(p.inventory).find(name => 
                                                        name.includes(searchKeyword) && p.inventory[name] > 0
                                                                );

                                                                        if (!realItemName) return message.reply(`❌ 你的背包裡沒有包含「${searchKeyword}」的可使用物品！`);

                                                                                // 1. 定義消耗品效果
                                                                                        const itemEffects = {
                                                                                                    // --- 補血類 ---
                                                                                                                "🧪 小型生命藥水": { hp: 30, msg: "喝下了小型藥水，恢復了 30 點 HP！" },
                                                                                                                            "🧪 中型生命藥水": { hp: 100, msg: "喝下了中型藥水，恢復了 100 點 HP！" },
                                                                                                                                        "🧪 大型生命藥水": { hp: 300, msg: "喝下了大型藥水，恢復了 300 點 HP！" },
                                                                                                                                                    "🧪 超大型藥水": { hp: 1000, msg: "喝下了神級藥水，恢復了 1000 點 HP！" },
                                                                                                                                                                "🍙 過期飯糰": { hp: 15, msg: "吃了過期飯糰... 肚子有點痛，但恢復了 15 點 HP。" },
                                                                                                                                                                            "🩹 急救包": { hp: 200, msg: "使用了急救包，傷口癒合了，恢復 200 點 HP！" },
                                                                                                                                                                                        "🍪 幸運餅乾": { hp: 50, msg: "咬碎了幸運餅乾，恢復 50 點 HP，感覺今天會走運！" },
                                                                                                                                                                                                    
                                                                                                                                                                                                                // --- Buff 類 (暫時以訊息替代，未來可加入戰鬥系統) ---
                                                                                                                                                                                                                            "🧪 力量藥劑": { atk: 20, msg: "喝下了力量藥劑，感覺渾身充滿了肌肉！(ATK暫時提升)" },
                                                                                                                                                                                                                                        "🧪 鐵壁藥劑": { def: 20, msg: "喝下了鐵壁藥劑，皮膚變得像鋼鐵一樣硬！(DEF暫時提升)" },
                                                                                                                                                                                                                                                    "⚡ 能量飲料": { hp: 20, msg: "大口乾掉能量飲料，精神百倍！恢復 20 點 HP。" },
                                                                                                                                                                                                                                                                "🧪 抗寒合劑": { msg: "喝下了抗寒合劑，現在去凍原不會感冒了！" },
                                                                                                                                                                                                                                                                            "🌀 加速捲軸": { msg: "撕開了加速捲軸，你的移動速度變得飛快！" }
                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                            const effect = itemEffects[realItemName];
                                                                                                                                                                                                                                                                                                    if (!effect) return message.reply(`🤔 **${realItemName}** 似乎不是直接使用的消耗品（可能是材料）。`);

                                                                                                                                                                                                                                                                                                            // 2. 執行效果
                                                                                                                                                                                                                                                                                                                    // 確保玩家數值存在
                                                                                                                                                                                                                                                                                                                            p.hp = p.hp || 100;
                                                                                                                                                                                                                                                                                                                                    p.maxHp = p.maxHp || 100;

                                                                                                                                                                                                                                                                                                                                            if (effect.hp) {
                                                                                                                                                                                                                                                                                                                                                        const oldHp = p.hp;
                                                                                                                                                                                                                                                                                                                                                                    p.hp = Math.min(p.maxHp, p.hp + effect.hp); // 不能超過血量上限
                                                                                                                                                                                                                                                                                                                                                                                const healed = p.hp - oldHp;
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                        if (healed <= 0 && p.hp >= p.maxHp) {
                                                                                                                                                                                                                                                                                                                                                                                                                        return message.reply(`❤️ 你的體力已經是滿的 (${p.hp}/${p.maxHp})，不需要浪費藥水！`);
                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                    // 3. 扣除物品並存檔
                                                                                                                                                                                                                                                                                                                                                                                                                                                            p.inventory[realItemName] -= 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (p.inventory[realItemName] <= 0) delete p.inventory[realItemName]; // 歸零則刪除鍵值

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            players[message.author.id] = p;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fs.writeFileSync('./players.json', JSON.stringify(players, null, 2));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // 4. 回傳結果
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    let resultLabel = effect.msg;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (effect.hp) resultLabel += `\n❤️ **HP:** \`${p.hp} / ${p.maxHp}\``;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return message.reply(`✨ **使用成功！**\n${resultLabel}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };